# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ee0f397ad661820c95cdb12e087f1f8badfa17ec94082a289db26e9221febda7f6c543ef488ba7ec87db456868fc67029f5946ec1fa4e4d004a46736e37b7ba

test:
  secret_key_base: 9115634d17708c80bafbe24de6678ecd783fae1deb3067b75e07036afed3751d69b312a50177e422cd20c9fbb6588a82cc3be0dbf60edd8583af650e8fe99454

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
